# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 17:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_auto_20170411_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 11, 17, 35, 41, 138736, tzinfo=utc)),
        ),
    ]
