# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 18:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_auto_20170411_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 11, 18, 17, 19, 659799, tzinfo=utc)),
        ),
    ]
