# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 20:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0010_auto_20170411_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 2, 20, 41, 31, 866642, tzinfo=utc)),
        ),
    ]
