# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 18:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0011_auto_20170502_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 3, 18, 42, 3, 870156, tzinfo=utc)),
        ),
    ]
